name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/codeguard_sftp
          chmod 600 ~/.ssh/codeguard_sftp

      - name: Deploy to server
        run: |
          ssh \
            -i ~/.ssh/codeguard_sftp\
            -o IdentitiesOnly=yes \
            -o PreferredAuthentications=publickey \
            -o PubkeyAuthentication=yes \
            -o PasswordAuthentication=no \
            -o KbdInteractiveAuthentication=no \
            -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ${{ secrets.SSH_PATH }}
          pwd
          git fetch --all
          git clean -f -e .env
          git reset --hard origin/master
          EOF
